### ISSUE TITLE
Switching boots doesn't update gravity correctly

### ISSUE THREAD

**Issue by ParadoxBomb** [Mysteryem/TMT_Gravity_Mod#10]
Similar to issue #8 , if you equip the anti-grav boots, land on a ceiling, and then switch the boots in your armor slot without removing your boots first, you will stay flipped with the new boots equipped.

https://puu.sh/qzxYN/03133b1f0e.png
https://puu.sh/qzy0W/8fb54e1c00.png
https://puu.sh/qzy24/431593eb0d.png
https://puu.sh/qzy2Y/d53f5f258a.png

**Comment by Mysteryem** [comment]
I had messed up the if statement at https://github.com/Mysteryem/TMT_Gravity_Mod/blob/fbcab4ab88ccbe35577d7078be7c5fb7b8d21a34/src/main/java/uk/co/mysterymayhem/gravitymod/GravityManagerCommon.java#L74
